### PR TITLE
feat: add vpc

### PR DESCRIPTION
**Pull request by hungran**

### CODE REVIEW

**Comment by hungran** [comment]
atlantis plan

**Comment by hungran** [comment]
atlantis plan

**Comment by hungran** [comment]
atlantis plan

**Comment by hungran** [comment]
atlantis plan

**Comment by hungran** [comment]
atlantis plan

**Comment by hungran** [comment]
atlantis apply

**Review by qmauvnt — APPROVED** [review]
image

**Comment by hungran** [comment]
atlantis apply

**Comment by hungran** [comment]
atlantis apply

**Pull request merged**
